### ISSUE TITLE
Aligning the bottom bar in mobile view

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/Stooler#124]
Align the street address,email and phone number in bottom horizontally in mobile view instead of vertical.

**Comment by shivamsouravjha** [comment]
Sure go ahead @logicalahara

**Comment by logicalahara** [comment]
as this is a frontend issue,do I need to follow other steps other than these ?

1. cd frontend/
2. npm install
3. npm start

**Comment by shivamsouravjha** [comment]
These steps are it @logicalahara

**Comment by daptheHuman** [comment]
hi you can assign me for this

**Comment by logicalahara** [comment]
Hey @shivamsouravjha, as discussed, I've aligned all fields in horizontal view on mobile front. Pl have a look

Also, Please do add "hacktoberfest-accepted'" tag to the PR. Thanks.

**Comment by shivamsouravjha** [comment]
Made a comment for your PR,have a look at it
